"""The two documents this project generates for other tools: a Hugging Face
model card and an Ollama Modelfile.

Both are written from `config.yaml` and the adapter's own config, so they
cannot drift from what was actually trained.
"""

from __future__ import annotations

import datetime
import json
from pathlib import Path

from dragon.config import Config

CHATML_TEMPLATE = """{{- if .System }}<|im_start|>system
{{ .System }}<|im_end|>
{{ end }}{{- range .Messages }}<|im_start|>{{ .Role }}
{{ .Content }}<|im_end|>
{{ end }}<|im_start|>assistant
"""

CHATML_STOPS = ["<|im_end|>", "<|im_start|>"]


def adapter_facts(config: Config) -> dict:
    path = config.adapter_dir / "adapter_config.json"
    if path.exists():
        try:
            return json.loads(path.read_text())
        except json.JSONDecodeError:
            pass
    return config.lora_config()


def model_card(config: Config, *, fused: bool, private: bool) -> str:
    facts = adapter_facts(config)
    lora = facts.get("lora_parameters", {})
    today = datetime.date.today().strftime("%d %B %Y")
    what = "the fused model of" if fused else "a LoRA adapter for"
    library = "mlx"
    tags = ["lora", "mlx", "writing-style", "fine-tune"]
    if private:
        tags.append("private")

    settings = "\n".join(
        [
            f"- iterations {facts.get('iters')}, batch {facts.get('batch_size')}, "
            f"learning rate {facts.get('learning_rate')}",
            f"- layers {facts.get('num_layers')}, max sequence {facts.get('max_seq_length')}",
            f"- LoRA rank {lora.get('rank')}, scale {lora.get('scale')}, "
            f"dropout {lora.get('dropout')}",
            "- keys: " + ", ".join(lora.get("keys", [])),
        ]
    )

    stats = config.root / "data" / "stats.json"
    corpus_line = ""
    if stats.exists():
        try:
            s = json.loads(stats.read_text())
            corpus_line = (
                f"Trained on {s['train']:,} brief-and-prose pairs, "
                f"{s['target_words']:,} words of target text.\n\n"
            )
        except (json.JSONDecodeError, KeyError):
            corpus_line = ""

    return f"""---
base_model: {config.base_model}
library_name: {library}
license: {config.license}
language: [en]
tags: [{", ".join(tags)}]
---

# {config.model_name} — {what} one writer's voice

A rank-{lora.get("rank", "?")} LoRA {"fused into" if fused else "on"} `{config.base_model}`,
trained on one person's published writing. It learns the register — sentence
length, rhythm, vocabulary, the shape of an argument — and very little else.

{corpus_line}It does not reliably know facts, not even facts that were in its training
corpus, and it will invent them fluently. Every output is a first draft for the
author to read, correct and sign.

Built {today} with [mlx-lm](https://github.com/ml-explore/mlx-lm) on Apple
silicon, using [TrainYourDragon](https://github.com/thejustinjames/TrainYourDragon).

## The system prompt

The adapter was trained with this prompt on every example, and expects it:

```
{" ".join(config.system_prompt.split())}
```

## Load it

```python
from mlx_lm import load, generate
{_load_snippet(config, fused)}
```

## Training configuration

{settings}

## What it is not

Not a writer, not a source of facts, and not a way round any disclosure
obligation. A model trained to write in a named person's voice is an
impersonation kit in the wrong hands; keep it private unless every person whose
writing is in the corpus has agreed otherwise.
"""


def _load_snippet(config: Config, fused: bool) -> str:
    if fused:
        return 'model, tok = load("<this repo>")'
    return (
        "from huggingface_hub import snapshot_download\n"
        'adapter = snapshot_download("<this repo>")\n'
        f'model, tok = load("{config.base_model}", adapter_path=adapter)'
    )


def modelfile(config: Config, source_dir: Path, *, params: dict | None = None) -> str:
    export = config.raw.get("export") or {}
    ollama = export.get("ollama") or {}
    template = ollama.get("template", CHATML_TEMPLATE)
    stops = ollama.get("stop", CHATML_STOPS)
    settings = {"temperature": 0.7, "top_p": 0.9, "num_ctx": 8192}
    settings.update(ollama.get("parameters") or {})
    settings.update(params or {})

    lines = [
        f"# {config.model_name} for Ollama, built from the dequantised fused model.",
        "# Generated by `dragon export`; edit config.yaml, not this file.",
        f"FROM {source_dir}",
        "",
        f'TEMPLATE """{template}"""',
        "",
        f'SYSTEM """{" ".join(config.system_prompt.split())}"""',
        "",
    ]
    lines += [f"PARAMETER {k} {v}" for k, v in settings.items()]
    lines += [f"PARAMETER stop {s}" for s in stops]
    return "\n".join(lines) + "\n"
